id = "hatsune-miku-by-vai-theme"
name = "Hatsune Miku Theme"
version = "0.0.6"
schema_version = 1
authors = ["Vadim Khristenko <vadim@vai-rice.space>"]
description = "This extension provides a Hatsune Miku theme for Zed editor."
repository = "https://github.com/Vadim-Khristenko/HatsuneMikuEditorTheme"
license = "MIT"
